apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
spec:
  template:
    spec:
      containers:
        - name: init-container
          image: postgres:latest
          command: ["/bin/sh", "-c"]
          args:
            - psql -U postgres -d school -a -f /etc/config/init.sql
          envFrom:
            - configMapRef:
                name: postgres-init
      restartPolicy: Never
  backoffLimit: 4
